from .auth import router as auth_router
from .competency import router as competency_router
from .matrix import router as matrix_router
from .questionnaire import router as questionnaire_router
from .handbook import router as handbook_router
from .report import router as report_router
from .file import router as file_router
from .user_settings import router as user_settings_router
from .practice import router as practice_router
from .roleplay import router as roleplay_router
from .vision_practice import router as vision_practice_router
